name: Lint

on: [push, pull_request]

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: npm install, build, and lint
        run: |
          yarn install
          yarn run build
          npm run-script lint