name: Release CI

on:
  push:
    branches:
      - main
  check_suite:
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: yarn install
      - run: npm test

      - name: Configure CI Git User
        run: |
          git config --global user.name '@jeswr'
          git config --global user.email 'jesse.wright@anu.edu.au'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/schimatos/ldfields
        env:
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}

      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull

      - name: Install Packages
        run: yarn install

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@ldfields:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: | 
          npx lerna publish --yes --conventional-commits --no-private --message "chore: release new versions"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
